from abc import ABC, abstractmethod

class MainViewInterface(ABC):
    @abstractmethod
    def set_presenter(self, presenter): ...
    @abstractmethod
    # def clear_grid(self): ...
    # @abstractmethod
    def update_cards(self, cards, clear_grid: bool): ...
    @abstractmethod
    def update_fetch_btn_state(self, text: str, state: bool): ...
